### ISSUE TITLE
cldfbench makecldf fails if not in a git repository with 1+ commit

### ISSUE THREAD

**Issue by SimonGreenhill** [cldf/cldfbench#64]
I got this error in a newly initialised repository with no check-ins. Looks like `GitPython` doesn't like this:

```shell
Traceback (most recent call last):
  File "/Users/simon/projects/lexibank2/env/bin/cldfbench", line 11, in <module>
    load_entry_point('cldfbench', 'console_scripts', 'cldfbench')()
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/cldfbench/__main__.py", line 78, in main
    return args.main(args) or 0
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/pylexibank/commands/makecldf.py", line 23, in run
    with_dataset(args, 'makecldf', dataset=dataset)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/cldfbench/cli_util.py", line 153, in with_dataset
    res = func(*arg, args)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/pylexibank/dataset.py", line 217, in _cmd_makecldf
    super()._cmd_makecldf(args)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/cldfbench/dataset.py", line 205, in _cmd_makecldf
    self.cmd_makecldf(args)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/pylexibank/cldf.py", line 100, in __exit__
    super().__exit__(exc_type, exc_val, exc_tb)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/cldfbench/cldf.py", line 98, in __exit__
    self.write(**self.objects)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/pylexibank/cldf.py", line 36, in write
    super().write(**kw)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/cldfbench/cldf.py", line 111, in write
    srcs.append(self.dataset.repo.json_ld())
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/cldfcatalog-1.3.0-py3.7.egg/cldfcatalog/repository.py", line 116, in json_ld
    res['dc:created'] = self.describe()
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/cldfcatalog-1.3.0-py3.7.egg/cldfcatalog/repository.py", line 95, in describe
    return self.repo.git.describe('--always', '--tags')
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/GitPython-3.1.0-py3.7.egg/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/GitPython-3.1.0-py3.7.egg/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Users/simon/projects/lexibank2/env/lib/python3.7/site-packages/GitPython-3.1.0-py3.7.egg/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git describe --always --tags
  stderr: 'fatal: Not a valid object name HEAD'
```

**Comment by SimonGreenhill** [comment]
(i.e. GitPython calls `git describe --always --tags` , which returns a fatal error because there's nothing to describe)

**Comment by SimonGreenhill** [comment]
Hmm, I thought I'd run `git init` but no `git commit`'s

**Comment by xrotwang** [comment]
Ah, ok. Yes, that seems possible. I'm always a bit hesitant when it comes to intercepting/wrapping errors from an underlying library - because that would mean 
1. "we can do better" in terms of  error messaging (which may not be the case, considering the rather broad `GitCommandError`), and
2. cut `cldfbench` off from improvements in `gitpython` (for this particular issue)

**Comment by SimonGreenhill** [comment]
Yeah this is probably a wontfix then, if not it should go upstream to gitpython. Either way it's not a major show stopper, and this issue documents the problem and solution ("commit something")
