### ISSUE TITLE
requirements.txt where

### ISSUE THREAD

**Issue by martino-vic** [cldf/cldfbench#81]
Is there something like a requirements.txt file somewhere in CLDF repositories? I made the mistake of upgrading one of the dependecies (csvw) of the lexibank-script within the virtual environment and I think this is the cause for the script running into errors now. So I wanted to downgrade csvw again but I can't find the information on which version the lexibank-script ran while it was still working. Does anyone have experience with these kind of issues?

**Comment by xrotwang** [comment]
That said, which error are you running into?

**Comment by martino-vic** [comment]
Thank you, will try it out! This is the full error message:

INFO    running _cmd_makecldf on ronatasbertawot ...
INFO    added sources
INFO    added concepts
INFO    added languages
Traceback (most recent call last):
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/segments/profile.py", line 104, in from_file
    tg = TableGroup.from_file(fname)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/csvw/metadata.py", line 1039, in from_file
    res = cls.fromvalue(data or get_json(fname))
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/csvw/metadata.py", line 185, in get_json
    return json.load(f, object_pairs_hook=collections.OrderedDict)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/viktor/Documents/cldfvenv3.9/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/cldfbench/__main__.py", line 84, in main
    return args.main(args) or 0
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/commands/makecldf.py", line 24, in run
    with_dataset(args, 'makecldf', dataset=dataset)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/cldfbench/cli_util.py", line 153, in with_dataset
    res = func(*arg, args)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/dataset.py", line 218, in _cmd_makecldf
    super()._cmd_makecldf(args)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/cldfbench/dataset.py", line 206, in _cmd_makecldf
    self.cmd_makecldf(args)
  File "/home/viktor/Documents/GitHub/rtbwestoldturkic/lexibank_rtbwestoldturkic.py", line 131, in cmd_makecldf
    for lex in args.writer.add_forms_from_value(
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/cldf.py", line 228, in add_forms_from_value
    kw_ = self.add_form(with_morphemes=with_morphemes, **kw_)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/cldf.py", line 198, in add_form
    self.tokenize(kw, form, **(dict(profile=profile) if profile else {})) or [])
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/cldf.py", line 128, in tokenize
    if self.dataset.tokenizer:
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/dataset.py", line 175, in tokenizer
    for k, p in self.orthography_profile_dict.items()}
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/dataset.py", line 148, in orthography_profile_dict
    return {k: Profile.from_file(str(p), form='NFC') for k, p in res.items()}
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/pylexibank/dataset.py", line 148, in <dictcomp>
    return {k: Profile.from_file(str(p), form='NFC') for k, p in res.items()}
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/segments/profile.py", line 107, in from_file
    tg = TableGroup.fromvalue(cls.MD)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/csvw/metadata.py", line 430, in fromvalue
    return cls(**cls.partition_properties(d))
  File "<attrs generated init csvw.metadata.TableGroup>", line 39, in __init__
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/csvw/metadata.py", line 1402, in converter_tables
    res.append(Table.fromvalue(vv) if isinstance(vv, dict) else vv)
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/csvw/metadata.py", line 430, in fromvalue
    return cls(**cls.partition_properties(d))
  File "<attrs generated init csvw.metadata.Table>", line 46, in __init__
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/csvw/metadata.py", line 1166, in __attrs_post_init__
    raise ValueError('url property is required for Tables')
ValueError: url property is required for Tables

**Comment by xrotwang** [comment]
Ah, you are running into the issue fixed here
https://github.com/cldf/segments/commit/9a2204ac72e1542f2a7140d11d9d8411be9198c4
So `pip install -U segments` should help.

**Comment by martino-vic** [comment]
Ah, okay nice. I think this seems to have fixed this error. I have another error now, but that's a different story. Thanks for helping!
