### ISSUE TITLE
Key Error while looping through SenseTable

### ISSUE THREAD

**Issue by martino-vic** [cldf/cldfbench#86]
I have a problem in [this repository](https://github.com/martino-vic/gerstnerhungarian). The .map command suddenly broke today, and I don't know exactly after which change or why. I've tried to understand the script [map.py](https://github.com/martino-vic/gerstnerhungarian/blob/main/gerstnerhungariancommands/map.py) but it's a bit cryptic to me, just as the traceback, because there are a lot of imports happening from libraries I'm not familiar with. I thought that this might be some trivial error for someone who's more familiar with the dependencies, that's why I thought opening an issue would make sense. Thank you in advance for any hints.

```
cldfbench gerstnerhungarian.map
Traceback (most recent call last):
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/venv/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/venv/lib/python3.8/site-packages/cldfbench/__main__.py", line 89, in main
    return args.main(args) or 0
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/gerstnerhungariancommands/map.py", line 32, in run
    entry = sense.entries[0]
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/venv/lib/python3.8/site-packages/pycldf/orm.py", line 369, in entries
    return self.all_related('entryReference')
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/venv/lib/python3.8/site-packages/pycldf/orm.py", line 202, in all_related
    return DictTuple(self.dataset.get_object(TERMS[relation].references, fk) for fk in fks)
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/venv/lib/python3.8/site-packages/pycldf/util.py", line 88, in __new__
    return super(DictTuple, cls).__new__(cls, tuple(items))
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/venv/lib/python3.8/site-packages/pycldf/orm.py", line 202, in <genexpr>
    return DictTuple(self.dataset.get_object(TERMS[relation].references, fk) for fk in fks)
  File "/home/viktor/Documents/GitHub/gerstnerhungarian/venv/lib/python3.8/site-packages/pycldf/dataset.py", line 852, in get_object
    return self._objects[table][id_] if not pk else self._objects_by_pk[table][id_]
KeyError: '3296-hah'
```

**Comment by LinguList** [comment]
It has nothing to do with cldfbench, but with the map command and the keys you use. As you can see, there's a key error with the key 2396-hah. So you should check if you find the key in your data or not. If you don't find it, you see that there are some assumptions wrong or some keys are not corresponding across the tables of your data.

**Comment by LinguList** [comment]
So I suggest to close this and reopen in your respective repository.

**Comment by martino-vic** [comment]
Fair point.
